### ISSUE TITLE
TypeName does not work properly

### ISSUE THREAD

**Issue by dragitz** [frostycpu/FinalesFunkeln#2]
Here's a screenshot: http://i.imgur.com/9ICuZ84.png

Maybe I'm doing something wrong, but I can't seem to make it work
Code:
`{
	"TypeName":"com.riotgames.platform.game.PracticeGameConfig",
	"allowSpectators":"NONE",
	"gameName":"LobbyTest",
	"maxNumPlayers":2,
	"gameMutators":[],
	"gameTypeConfig":1,
	"gamePassword":"b",
	"gameMode":"CLASSIC",
	"region":"",
    "passbackUrl":null,
	"passbackDataPacket":null,
    "gameMap":{
			"TypeName":"com.riotgames.platform.game.map.GameMap",
			"mapId":11,
			"description":"Type name hates me",
			"totalPlayers":10,
			"minCustomPlayers":1,
			"name":"SummonersRift",
			"displayName":"Summoner\'s Rift",
			"futureData":null,
			"dataVersion":null
			}
	
}`

**Comment by dragitz** [comment]
Here's a better display of the code 
http://pastebin.com/Y1eRBP7d

**Comment by frostycpu** [comment]
Seems to be a bug with nested objects, will fix it asap.

Dumping the packet as an object is a pretty neat idea, I'll take a look at it!

**Comment by dragitz** [comment]
Have you done some changes? If so, can you upload the changes? =)

**Comment by frostycpu** [comment]
Not yet, pretty busy atm. I will fix it when I find some time.
