### ISSUE TITLE
Suddently unable to compile it again + msbuild logs(tested on 2 different computers)

### ISSUE THREAD

**Issue by dragitz** [frostycpu/FinalesFunkeln#5]
Hello! I had to format my pc for other reasons and now I can not compile it again (I must miss something)
I did try to compile on a different computer but no success.

Here's the msbuild log: http://pastebin.com/guQtM9wv
I have tried to reinstall my .net framework, downgrade it to 4.5, reinstall to 4.6, install the sdk. But sadly nothing could be done.

Console: http://i.imgur.com/tPatwf4.png

I did looked at the files that gave me the error and it's totally non sense, your files are perfect. I'm sure I'm missing something from the W7 reinstall.

Do you have any possible idea in mind? Thanks!

**Comment by frostycpu** [comment]
Looks like you're missing C# 6.0 support.
E.g. this line has a syntax error
`public List<View> Views { get; } = new List<View>();`
because getter only auto-properties where not allowed prior to C# 6.
Hope this helps!

**Comment by dragitz** [comment]
Oh my~
Had to download and extra package, thank you master! :+1:
