### ISSUE TITLE
FinalesFunkeln stops working after clicking the profile icon (Error.log included)

### ISSUE THREAD

**Issue by dragitz** [frostycpu/FinalesFunkeln#6]
Logs: http://pastebin.com/raw/pbqaTJns

-Open both lol and ff
-Try to see the profile
-ff crashes

Not a big deal but it happends, so yeah

**Comment by frostycpu** [comment]
I'm not able to reproduce it. Which server are you playing on?

**Comment by dragitz** [comment]
Euw, hovering over a friend with your mouse also makes ff crash

On pbe as soon as I join ff crashes (I can simply reopen it but I can't read some info)
