### ISSUE TITLE
TypeName is still bugged and doesn't get exported when exporting to Json

### ISSUE THREAD

**Issue by dragitz** [frostycpu/FinalesFunkeln#8]
http://i.imgur.com/sXJGFFi.png

Just replace the sumid and the pageid with your http://pastebin.com/raw/UFQpJwnb

Great feature

**Comment by frostycpu** [comment]
Oh crap I forgot arrays. Should be an easy fix.

**Comment by dragitz** [comment]
I'm using the latest update and it still does not work http://i.imgur.com/v2Av71T.png
Am I doing something wrong?
Exported json with TypeName http://pastebin.com/raw/hyiYSRYk
